### ISSUE TITLE
Give option to disable bluetooth indicator in wingpanel

### ISSUE THREAD

**Issue by moonmehta** [elementary/switchboard-plug-bluetooth#42] opened 2018-05-03 10:29 UTC
Unity had an option to disable the bluetooth indicator in the status/menu bar.

![screenshot from 2018-05-03 10-16-19](https://user-images.githubusercontent.com/22585732/39571955-f8ebd612-4eea-11e8-9515-74bc0766a0e4.png)

It will be useful to have the same on elementary as I don't use Bluetooth at all and the indicator is taking up unnecessary space.

**Comment by danirabbit** [comment] 2024-05-23 17:46
I'm going to close this as a duplicate of https://github.com/elementary/wingpanel/issues/213

Essentially after some discussion this is something that's better done as a feature of the panel than individually per plugin

**Closed by danirabbit** 2024-05-23 17:46 UTC
Labels: Status: Blocked, Priority: Wishlist
