### ISSUE TITLE
Bluetooth turn on after sleep

### ISSUE THREAD

**Issue by gasparinzsombor** [elementary/switchboard-plug-bluetooth#159] opened 2021-01-12 19:03 UTC
If I wake up the computer from sleep, the bluetooth turns on, doesn't matter if it was before the sleep.

**Comment by vjr** [comment] 2021-01-26 18:47
Duplicate of https://github.com/elementary/wingpanel-indicator-bluetooth/issues/117

**Closed** 2021-01-27 23:52 UTC
