### ISSUE TITLE
bluetooth auto on

### ISSUE THREAD

**Issue by prvn93** [elementary/switchboard-plug-bluetooth#107] opened 2020-01-22 04:59 UTC
Bluetooth is turning on automatically after resuming from suspend.

**Comment by ivcosla** [comment] 2020-03-15 10:49
I'm having the same issue. Could upload any report in case this is happening only in some specific hardware.

**Comment by NathanBnm** [comment] 2020-04-15 16:32
I have the same issue. See here too: https://github.com/elementary/switchboard-plug-bluetooth/issues/21

**Comment by ryonakano** [comment] 2020-04-16 07:11
Closing as a duplicate of #21

**Closed by ryonakano** 2020-04-16 07:11 UTC
