### ISSUE TITLE
Bluetooth automatically turns on after waking the pc from sleep

### ISSUE THREAD

**Issue by shubhamthedev** [elementary/switchboard-plug-bluetooth#130] opened 2020-06-22 03:32 UTC
![Screenshot from 2020-06-22 09-01-52](https://user-images.githubusercontent.com/33488761/85246028-0c58d180-b467-11ea-9fbc-e48a86930910.png)

**Comment by jeremypw** [comment] 2020-07-18 18:42
This is a duplicate of #21

**Closed** 2022-09-07 19:25 UTC
Labels: Status: Duplicate
